# New ports collection makefile for:	php5-meta
# Date created:				2013-11-13
# Whom:					Dachi Chang <femc7488@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	php5-meta
PORTVERSION=	1.0
CATEGORIES=	arkports
MASTER_SITES=	# none
DISTFILES=	# none

MAINTAINER=	femc7488@gmail.com
COMMENT=	Awesome Rapid Kit php5 programming language

RUN_DEPENDS=	ark-php5-config>=0:${PORTSDIR}/arkports/php5-config \
		php5>=0:${PORTSDIR}/lang/php5 \
		php5-extensions>=0:${PORTSDIR}/lang/php5-extensions

NO_WRKSUBDIR=	yes
NO_BUILD=	yes
NO_STAGE=	yes
NO_PACKAGE=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
