# New ports collection makefile for:	proftpd-meta
# Date created:				2013-12-22
# Whom:					Dachi Chang <femc7488@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	proftpd-meta
PORTVERSION=	1.0
CATEGORIES=	arkports
MASTER_SITES=	# none
DISTFILES=	# none

MAINTAINER=	femc7488@gmail.com
COMMENT=	Awesome Rapid Kit proftpd ftp server

RUN_DEPENDS=	ark-proftpd-config>=0:${PORTSDIR}/arkports/proftpd-config \
		proftpd>=0:${PORTSDIR}/ftp/proftpd

NO_WRKSUBDIR=	yes
NO_BUILD=	yes
NO_STAGE=	yes
NO_PACKAGE=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
