# New ports collection makefile for:	screen-meta
# Date created:				2013-10-17
# Whom:					Dachi Chang <femc7488@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	screen-meta
PORTVERSION=	1.0
CATEGORIES=	arkports
MASTER_SITES=	# none
DISTFILES=	# none

MAINTAINER=	femc7488@gmail.com
COMMENT=	Awesome Rapid Kit screen multiplexer

RUN_DEPENDS=	ark-screen-config>=0:${PORTSDIR}/arkports/screen-config \
		screen>=0:${PORTSDIR}/sysutils/screen

NO_WRKSUBDIR=	yes
NO_BUILD=	yes
NO_STAGE=	yes
NO_PACKAGE=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
