# New ports collection makefile for:	console-editor
# Date created:				2013-10-19
# Whom:					Dachi Chang <femc7488@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	console-editor
PORTVERSION=	1.0
CATEGORIES=	arkports
MASTER_SITES=	# none
DISTFILES=	# none

MAINTAINER=	femc7488@gmail.com
COMMENT=	Awesome Rapid Kit console editor

RUN_DEPENDS=	ark-vim-lite-config>=0:${PORTSDIR}/arkports/vim-lite-config \
		vim-lite>=0:${PORTSDIR}/editors/vim-lite

NO_WRKSUBDIR=	yes
NO_BUILD=	yes
NO_STAGE=	yes
NO_PACKAGE=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
